# Specify the Docker image to use
image: registry.gitlab.com/pages/hugo:latest

# Define stages for CI/CD pipeline
stages:
  - build
  - deploy

# Job to build the website
build:
  stage: build
  script:
    - hugo

# Job to deploy the website
deploy:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public/
    - mv public public_html # Assuming your web server root directory is public_html
  artifacts:
    paths:
      - public_html
  only:
    - master  # Deploy only when changes are pushed to master branch
