image: registry.gitlab.com/pages/hugo:latest  # Używa obrazu Docker dla Hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo --my-themes
  artifacts:
    paths:
      - public
  only:
    - main