image: registry.gitlab.com/MateuszFamulski/dlaciebie/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public/
  only:
    - main
